Repository php/web-php, pull requests merged in 2023-12, with the labels that each got.

#848 Add actions to manage statuses
  .github/workflows/close-needs-feedback.yml
  .github/workflows/remove-needs-feedback.yml
Labels: Waiting on Review

#847 Enhancement: Require and use PHP 8.2
  .github/workflows/integrate.yaml
  README.md
  composer.json
  composer.lock
Labels: Waiting on Review

#661 Enhancement: Enable `void_return` fixer
  .php-cs-fixer.php
  include/changelogs.inc
  include/do-download.inc
  include/errors.inc
  include/layout.inc
  include/prepend.inc
  include/results.inc
  include/shared-manual.inc
  include/site.inc
Labels: Status: Needs Triage

#406 Enhancement: Expose happy path
  .router.php
Labels: Waiting on Review

#647 Enhancement: Enable `trailing_comma_in_multiline` fixer
  .php-cs-fixer.php
  credits.php
  download-docs.php
  downloads.php
  elephpant.php
  error.php
  git-php.php
  images/elephpants.php
  include/branches.inc
  include/get-download.inc
  include/ip-to-country.inc
  include/langchooser.inc
  include/layout.inc
  include/results.inc
  include/shared-manual.inc
  include/site.inc
  index.php
  mailing-lists.php
  manual/add-note.php
  manual/vote-note.php
  mirror.php
  mirroring.php
  mod.php
  my.php
  releases/8.0/de.php
  releases/8.0/en.php
  releases/8.0/es.php
  releases/8.0/fr.php
  releases/8.0/it.php
  releases/8.0/ja.php
  releases/8.0/ka.php
  releases/8.0/nl.php
  releases/8.0/pt_BR.php
  releases/8.0/ru.php
  releases/8.0/tr.php
  releases/8.0/zh.php
  releases/8.2/release.inc
  releases/index.php
  results.php
  search.php
  sites.php
  src/autoload.php
  submit-event.php
  support.php
Labels: Status: Needs Triage

#585 Fix: Remove unused functions
  bin/createNewsEntry
  include/layout.inc
  include/results.inc
  include/site.inc
  quickref.php
  results.php
Labels: Waiting on Author
